### PR TITLE
request service should be removed before changing his definition

### PR DESCRIPTION
**Pull request by Druid33**
Without this change its not possible fill content to request body using `_request()` method.

I add some more info:

I had problem set json content to _request() method. After some research, diging into code i realize, it is not possible replace shared service with other shared service. One can replace shared service only with non-shared service.

```php
$di->set('service', {some_definition}, true);
// this line does not change service.
$di->set('service', {some_other_definition}, true);
// this line change service
$di->set('service', {some_other_definition}, false);
```
Its not possible change shared service with "array' notation like this:

```php
$di->set('service', {some_definition}, true);
// this line does not change service.
$di['service'] =  {some_other_definition};
```

Using "array" notation you only change service definition. but if shared service is resolved before, changing definition has not effect on next geting service

### CODE REVIEW

**Comment by ruudboon** [comment]
Thnx @Druid33 
Can you add a few tests for this as well?

Related to: https://github.com/phalcon/cphalcon/pull/14834

**Comment by Druid33** [comment]
ok, I try to find some time :)

**Comment by Druid33** [comment]
> Thnx @Druid33
> Can you add a few tests for this as well?
> 
> Related to: [phalcon/cphalcon#14834](https://github.com/phalcon/cphalcon/pull/14834)

Hi, finally i write test i promise a year ago...hope it will be enough.

**Comment by Jeckerson** [comment]
@Druid33 Thanks!

**Comment by Jeckerson** [comment]
Released in https://github.com/Codeception/module-phalcon4/releases/tag/v1.0.6

**Pull request merged**
